language: php
before_install: composer config -g github-oauth.github.com "$GITHUB_TOKEN"
install: composer install --prefer-dist && composer require phpoffice/phpexcel 1.8.1
script:
  - php -v
  - php vendor/bin/phpunit -v
  - ./check-code.sh
  - php vendor/bin/phpunit
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2