language: php
before_install: composer config -g github-oauth.github.com "$GITHUB_TOKEN"
install: composer install --prefer-dist && composer require phpoffice/phpspreadsheet 1.5.*
script:
  - php -v
  - php vendor/bin/phpunit -v
  - ./check-code.sh
  - php vendor/bin/phpunit -c phpunit.xml.dist
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
deploy:
  provider: heroku
  app: pepiscms-demo
  api_key:
    secure: Ixm+QZX1Y76DqVtpKDAxy7BpmRz1D9UYDNl3/WB/84mFOp/edsQvW4x0MQnRmz1ejIiRSEMw4deGygIqk2TpWlzMvp8706BAEpdiBti1Abcai5KV3+nCLtu8fYk/loXl49rOvppxrXS0P4/0s8to7OrI+duvrVT965nfcwbdP4REWfhSC/6oWkAZ7gcnsT4M/k3UQk2MjkshwWykIv7MYtAUAzJxZYCtsLCHt9GqI3wyMqRLc5qm2rkY9Mjtgw/JvKLZhOlevmr2G9Qz6bh6LekTwibTGHFXmq74h4MJD636Pa5dxADr4h5l2bzKdnucnsrwJuPicj+qvkkubVKdJbnW5FHq/9qmVfJEk+RzY1m1ONRzXGXEbrZnO6uvUuDxqskENcSDM2WsEMdH6flGcirSCqvy0s7rM2CVLLB9E8Nk956KH1LTGLhpvvid2eJKgtwYaKbZzHWf3BNOxiAPdmqq28Ngv5RxnvWRygMCrdOy/GJUOm1Q/nHlnW3rqvYe/s2fqv0kIC5hmubnjTNOCavfxZNJmBgQiytKJ10MRB7UIPlXUCUixdVT9pmH2uqJLgCIkcYmYKJqaANj74lhB+O4r1dwb/QPIlolC0AgTCP8osPJAIHbGs1QeoGdpPK7SmlhGJ/Fb7FNIMB7oMc2ue89GDjJC6jlfUsKpIyXwJ8=
jobs:
  include:
    - stage: deploy
      script: echo Deploy
      php: 7.2