language: php
before_install: composer config -g github-oauth.github.com "$GITHUB_TOKEN"
install: composer install --prefer-dist
script:
  - ./check-code.sh
  - composer require phpoffice/phpexcel 1.8.1 && phpunit
php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2